[metadata]
name = GMAP
description = A tool for calculating vibrational spectra
author = Kim E. van Adrichem
platforms = unix, linux, osx, win32
version = 0.0.1
classifiers =
    Programming Language :: Python :: 3

[options]
packages = 
    GMAP
    GMAP.src
    GMAP.helpers
include_package_data = True
install_requires = 
    MDAnalysis >= 0.20
    numba >= 0.58
    numpy >= 1.22, <=1.26
    
python_requires = 
    >=3.10


[options.extras_require]
testing = 
    flake8 >= 4.0
    numpydoc >= 1.6.0
    pydata-sphinx-theme >= 0.14
    pytest >= 6.0
    pytest-cov >= 2.0
    sphinx >= 7.2.6
    sphinx-design >= 0.5

[options.package_data]
* = 
    sourcefiles/*
    maps/*


[options.entry_points]
console_scripts =
    GMAP = GMAP.src.tools.CmdInterface:main
